[build]
  command = "npm i --verbose"
  publish = "."
  
  [template.environment]
  COUCHBASE_USERNAME = "COUCHBASE_USERNAME"
  COUCHBASE_PASSWORD = "COUCHBASE_PASSWORD"
  COUCHBASE_ENDPOINT = "COUCHBASE_ENDPOINT"
  COUCHBASE_BUCKET = "COUCHBASE_BUCKET"
